services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chinook_auto_increment
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgrest:
    image: postgrest/postgrest:v12.2.3
    ports:
      - "3001:3000"
    environment:
      PGRST_DB_URI: "postgres://postgres:postgres@postgres:5432/chinook_auto_increment"
      PGRST_DB_ANON_ROLE: "postgres"
      PGRST_OPENAPI_SERVER_PROXY_URI: "http://localhost:3001"
      PGRST_DB_SCHEMAS: "public"
    depends_on:
      postgres:
        condition: service_healthy

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: chinook_auto_increment
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "testuser", "-ptestpass"]
      interval: 5s
      timeout: 5s
      retries: 10
